version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs_m3h3/source/conf.py

# Optionally set the version of Python and requirements required to build your docs
# python:
#   version: 3.7
#   install:
#     - requirements: docs/requirements.txt
#     - method: setuptools
#       path: .
